
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Mhs extends javax.swing.JFrame {

    /**
     * Creates new form Mhs
     */
    public Mhs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtNim = new java.awt.TextField();
        txtNama = new java.awt.TextField();
        cbJk = new javax.swing.JComboBox<>();
        cbPr = new javax.swing.JComboBox<>();
        tbAdd = new javax.swing.JButton();
        tbSave = new javax.swing.JButton();
        tbExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemhs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Input Data Mahasiswa");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 10, 335, -1));

        label3.setText("Nama");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 104, -1, -1));

        label4.setText("Jenis Kelamin");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 134, -1, -1));

        label6.setText("Prodi ");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 164, -1, -1));

        label2.setText("Nim");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 74, -1, -1));
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 74, 184, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 104, 206, -1));

        cbJk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lk", "Pr" }));
        getContentPane().add(cbJk, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 134, 75, -1));

        cbPr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "SI" }));
        getContentPane().add(cbPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 164, 136, -1));

        tbAdd.setText("Add");
        tbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAddActionPerformed(evt);
            }
        });
        getContentPane().add(tbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 225, -1, -1));

        tbSave.setText("Save");
        getContentPane().add(tbSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 225, -1, -1));

        tbExit.setText("Exit");
        getContentPane().add(tbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 225, -1, -1));

        tablemhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablemhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 282, 494, 213));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAddActionPerformed
    try {
            String sql = "INSERT INTO tabel_mahasiswa VALUES ('"+txtNim.getText()+"','"+txtNama.getText()+"','"+cbJk.getSelectedItem()+"','"+cbPr.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJk;
    private javax.swing.JComboBox<String> cbPr;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private javax.swing.JTable tablemhs;
    private javax.swing.JButton tbAdd;
    private javax.swing.JButton tbExit;
    private javax.swing.JButton tbSave;
    private java.awt.TextField txtNama;
    private java.awt.TextField txtNim;
    // End of variables declaration//GEN-END:variables
}
